baseURL: https://jacquietran.com
languageCode: en
DefaultContentLanguage: en
title: Jacquie Tran | Researcher - Data analyst - Sport scientist
theme: anatole
summarylength: 10
enableEmoji: yes
enableRobotsTXT: yes
pygmentsUseClasses: yes
pygmentsCodeFences: yes
pygmentsCodefencesGuessSyntax: yes
markup:
  goldmark:
    renderer:
      unsafe: yes
taxonomies:
  category: categories
  series: series
  tag: tags
